steps:
- id: 'Install-Prereqs'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- id: 'Build-Prod-Pkg'
  name: 'gcr.io/cloud-builders/npm'
  waitFor: ['Install-Prereqs']
  args: ['run', 'build']
- id: 'Pull-docker-image'
  waitFor: ['Build-Prod-Pkg']
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/tic-tac-toe:latest']

- id: 'Build-Docker-Image'
  waitFor: ['Pull-docker-image']
  name: 'gcr.io/cloud-builders/docker'
  dir: 'src/flask'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/tic-tac-toe:$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/tic-tac-toe:latest',
         '--cache-from', 'gcr.io/$PROJECT_ID/tic-tac-toe:latest',
         '-f', 'Dockerfile',
         '.']

- id: 'Push-the-Docker-Image-to-GCR'
  waitFor: ['Build-Docker-Image']
  name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "gcr.io/$PROJECT_ID/tic-tac-toe:$SHORT_SHA"]

- id: 'Rename-image-hash'
  waitFor: ['Push-the-Docker-Image-to-GCR']
  name: 'ubuntu'
  dir: 'k8s-manifests'
  args: [ "sed", "-i", "s^image: tic-tac-toe^image: gcr.io/$PROJECT_ID/tic-tac-toe:$SHORT_SHA^g", "fe-deploy.yaml" ]

- id: 'Update-K8S'
  waitFor: ['Rename-image-hash']
  name: 'gcr.io/cloud-builders/kubectl'
  args: ["apply",'-f', 'k8s-manifests']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_K8S_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_K8S_CLUSTER}'

substitutions:
  _K8S_ZONE: us-east4-b # default value
  _K8S_CLUSTER: cluster # default value

images:
- 'gcr.io/$PROJECT_ID/tic-tac-toe:latest'
