apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fe
        visualize: 'true'
    spec:
      containers:
      - name: fe
        image: tic-tac-toe
        ports:
        - containerPort: 80
